trigger:
- master
- release/*

resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

phases:
  - template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
    parameters:
      agentOs: Windows
