trigger:
  branches:
    include:
    - 'main'
    - 'release/*'
    - 'internal/release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

schedules:
- cron: 0 9 * * 1
  displayName: "Run CodeQL3000 weekly, Monday at 2:00 AM PDT"
  branches:
    include:
    - release/2.1
    - release/6.0
    - release/7.0
    - main
  always: true

parameters:
# Parameters below are ignored in public builds.
#
# Choose whether to run the CodeQL3000 tasks.
# Manual builds align w/ official builds unless this parameter is true.
- name: runCodeQL3000
  default: false
  displayName: Run CodeQL3000 tasks
  type: boolean


phases:
  - template: ../templates/default-build.yml
    parameters:
      agentOs: Windows
      codeSign: true
      ${{ if or(eq(variables['Build.Reason'], 'Schedule'), and(eq(variables['Build.Reason'], 'Manual'), eq(parameters.runCodeQL3000, 'true'))) }}:
        codeSign: false
        beforeBuild: 
        - script: "echo ##vso[build.addbuildtag]CodeQL3000"
          displayName: 'Set CI CodeQL3000 tag'
        - task: CodeQL3000Init@0
          displayName: CodeQL Initialize
        afterBuild:
        - task: CodeQL3000Finalize@0
          displayName: CodeQL Finalize
      ${{ else }}:
        codeSign: false
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          buildArgs: '/p:OfficialBuild=true /p:Sign=true'
      variables: ${{ parameters.variables }}
